//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailRentingApp.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentingOfTradingArea
    {
        public int Id { get; set; }
        public int RentingId { get; set; }
        public int TradingAreaId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Renting Renting { get; set; }
        public virtual TradingArea TradingArea { get; set; }
    }
}
