//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailRentingApp.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TradingArea()
        {
            this.RentingOfTradingAreas = new HashSet<RentingOfTradingArea>();
        }
    
        public int Id { get; set; }
        public byte Floor { get; set; }
        public decimal AreaInSquareMeters { get; set; }
        public bool IsAirVenting { get; set; }
        public decimal CostPerDay { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentingOfTradingArea> RentingOfTradingAreas { get; set; }
    }
}
